---
output:
  rmdformats::html_clean:
    highlight: kate
---


```{r setup, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

# Accessing RStudio Server

To launch your own instance of R:

- Go to [notebooks.csc.fi](https://notebooks.csc.fi/#/) and log in using the Haka authentication service.
- Click on "Account" and then "Join Group".
- Click "Join" after adding this joining code: **cscdataanalysisr-9c4er**
- Find "R Data Analysis" in the dashboard and click on "Launch new". Note: there is also an environment called "RStudio Server", but we won't use that during the course.
- Wait for the virtual machine to start and click on "Open in browser" once the link appears.
- Your browser will open a new window with login and password details. Press "Click to copy password & proceed".
- This will open a new tab where you can enter a username ("**rstudio**") and paste your password to open up a new RStudio session.

Note: each RStudio session on [notebooks.csc.fi](https://notebooks.csc.fi/#/) lasts for 10 hours, after which it is automatically erased. We will cover ways to save your code and data for later work during this workshop!
