---
output:
  rmdformats::html_clean:
    highlight: kate
---


```{r setup, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

# Data visualization - independent exercises

#### **1. Getting the data**

**1.1** Just like we did yesterday, install the package `rjstat` if you do not have it already installed. Then load the necessary libraries by copy-pasting the following lines into an R script and running them in RStudio.

```r
install.packages("rjstat")

library(rjstat)
library(tidyverse)
```

**1.2** Retrieve coronavirus observations from the THL website. We will use the same data that we worked with yesterday.

Getting the data was covered in the Day 1 extra exercises, so you can run through the following code chunk in your Rstudio session. You can highlight the code below and copy-paste it into a new R script.

```r
# Getting the data
url.call <- "https://sampo.thl.fi/pivot/prod/en/epirapo/covid19case/fact_epirapo_covid19case.json?row=hcdmunicipality2020-445222&column=dateweek20200101-509030&filter=measure-444833"

# Read data into an R object
# select the object `COVID-19 cases in the infectious diseases registry`
data <- fromJSONstat(readLines(url.call, encoding = "UTF-8"))$`COVID-19 cases in the infectious diseases registry`

# Convert value column to numeric
data$value <- as.numeric(data$value)
```

#### **2. Data wrangling**

First, we will do some data wrangling to format the data for `ggplot2`. Go through each step carefully to form an understanding of what is happening as you are running through the code. Make sure to copy and run each line!

**2.1** Let's make a copy of the data and format them so that they are suitable for plotting with `ggplot2`.

```r
plotdata <- data
```

**2.2** Filter out NA values.

```r
plotdata <- plotdata %>% 
  filter(!is.na(value))
```

**2.3** There is a row in the column `dateweek20200101` that contains the word "Time" as an entry, rather than the year and week (checked 14.01.2021). Let's remove it!

```r
plotdata <- subset(plotdata, dateweek20200101 != "Time")
```

**2.4** Convert the column containing hospital districts (`hcdmunicipality2020`) into a factor.

```r
plotdata$region <- as.factor(plotdata$hcdmunicipality2020)
```

**2.5** Check the structure of the data. The output should look something like the example below (although the exact appearance might differ, depending on when you downloaded the data).
```r
str(plotdata)
```

```r
'data.frame':	1188 obs. of  4 variables:
 $ hcdmunicipality2020: chr  "Åland" "Åland" "Åland" "Åland" ...
 $ dateweek20200101   : chr  "Year 2020 Week 02" "Year 2020 Week 03" "Year 2020 Week 04" "Year 2020 Week 05" ...
 $ value              : num  0 0 0 0 0 0 0 0 0 0 ...
 $ region             : Factor w/ 22 levels "Åland","All areas",..: 1 1 1 1 1 1 1 1 1 1 ...
```

**2.6** Group the data by region to create regional sums (similar to yesterday's excercise, with regions corresponding to hospital districts).

```r
plotdata_sums <- plotdata %>%
  group_by(region) %>%
  summarise(observations = sum(value, na.rm = TRUE))
```

Ok! Now we're ready to create some plots.

#### **3. Exercises**

**3.1** Plot the regional sums of COVID-19 observations using `plotdata_sums`. Hint: use `geom_col()`.

```r
ggplot(data = plotdata_sums,
       aes(x = region, y = observations)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```

**3.2** Now let's create a line plot using the original `plotdata` data frame (which has the weekly values).
This plot does not look that great (yet!).

```r
ggplot(data = plotdata,
       aes(x = dateweek20200101, y = value)) +
  geom_line() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```

**3.3** One problem here is that we haven't yet grouped and coloured the data by region. Try fixing that!

```r
ggplot(data = plotdata,
       aes(x = dateweek20200101, y = value, group = region, colour = region)) +
  geom_line() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```

**3.4** Another thing we could do is to replace the years and weeks with more succinct labels. Let's use the `string` package to remove the words "Year" and "week".

```r
library(stringr)
plotdata$dateweek20200101 <- str_trim(str_replace(plotdata$dateweek20200101, 'Year', '')) 
plotdata$dateweek20200101 <- str_trim(str_replace(plotdata$dateweek20200101, 'Week', '')) 
```

**3.5** Try giving the plot more informative axis labels (such as "No. of COVID-19 cases" and "Week and year").

```r
ggplot(data = plotdata,
       aes(x = dateweek20200101, y = value, group = region, colour = region)) +
  geom_line() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
  labs(x = "Year and week", y = "No. of COVID-19 cases")
```

#### **4. Saving and exporting your script**

If you don't remember how to save and export your data from RStudio Server, follow the instructions set out in the **Starting with Data exercise sheet** (steps 7.3 and 7.4).

That's it in terms of exercises! Depending on the course schedule, there may be a chance to go through the solutions during the beginning of Day 3. However, if you're attending a two-day course feel unsure about how to solve some of the problems above, you can have a look at the completed exercise sheets on eLena.

Thanks for joining the course (so far!) and we hope you've found the contents useful!