---
output:
  rmdformats::html_clean:
    highlight: kate
---

```{=html}
<style>
  code {
    white-space : pre-wrap !important;
    word-break: break-word;
  }
</style>
```
```{r setup, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

# Data visualization - independent exercises

### **1. Getting the data**

**IMPORTANT:** There are two options for how to get the data. Choose one of them. If you already have the object `swallows_data` ready from the data manipulation exercise, continue straight to **2. Data wrangling**.

**Option 1:** On your own computer that has R and RStudio installed (see [here](https://e-learn.csc.fi/mod/url/view.php?id=2191) for instructions).

**Option 2:** On Notebooks as the rest of the course exercises.

#### **Option 1 using your own computer: start here**

Just like we did in the extra exercises for Data Manipulation, load the necessary libraries by copy-pasting the following lines into an R script and running them in RStudio. If you did not install the package `finbif` yet, install it first.

``` r
# installing the ´finbif´ package (if already installed, skip this line)
install.packages("finbif")

#loading the packages ´finbif´ and ´tidyverse´
library(finbif)
library(tidyverse)
```

Retrieve barn swallow observations from the FinBIF database. We will use the same data that we worked with in the Data Manipulation extra exercises.

Getting the data was covered in the Data manipulation extra exercises, so you can run through the following code chunk in your Rstudio session. You can highlight the code below and copy-paste it into a new R script.

``` r
# If you got an access token by email yesterday, skip this line and use the same token 
finbif_request_token("your@email.com")

# Setting the access token (replace the long string in quotation marks with the token you received by email)
Sys.setenv(FINBIF_ACCESS_TOKEN = "xtmSOIxjPwq0pOMB1WvcZgFLU9QBklauOlonWl8K5oaLIx8RniJLrvcJU4v9H7Et")

# Retrieve the data from FinBIF
swallows_data <- finbif_occurrence("Hirundo rustica", n=5000, select = c("default_vars", "bio_province"))
```

#### **Option 2 using Notebooks: start here**

Launch RStudio in Notebooks. Load the tidyverse package:

``` r
library(tidyverse)
```

Import an R data object into R:

``` r
swallows_data <- readRDS("/home/rstudio/shared/swallows_data.rds")
```

#### **Both options: continue from here!**

### **2. Data wrangling**

First, we will do some data wrangling to format the data for `ggplot2`. Go through each step carefully to form an understanding of what is happening as you are running through the code. Make sure to copy and run each line!

**2.1** Let's make a copy of the data and format them so that they are suitable for plotting with `ggplot2`. First, we will repeat the steps from yesterday to simplify the date format, remove double entries in `bio_province` and remove unlikely observations in winter. Copy-paste these lines in your R script and run them as they are.

``` r
# making a copy of the data
swallowplot <- swallows_data

# setting format of the column ´date_time´ to year-month-day
swallowplot$date_time = as.Date(format(swallowplot$date_time, "%Y-%m-%d"))

# removing observations in 2023 and before March 2022
swallowplot <- swallowplot %>% filter(date_time < "2023-01-01" & date_time > "2022-03-01")

# removing double entries in the column ´bio_province´ by replacing text with the function gsub
swallowplot$bio_province <- gsub(",.*", "", swallowplot$bio_province)
```

**2.2** Because we want to use the month in the column `date_time` for plotting, let's do some additional formatting of this column. What we do here is not particularly elegant and there are specialized packages for dealing with dates in R but, well, it works. In general there are always many different ways to do any data wrangling step in R. Copy-paste these lines to your R script and run them as they are.

``` r
# removing the year and the date from the column ´date_time´ with the function ´gsub´ to leave only the month 
swallowplot$date_time <- gsub("2022-", "", swallowplot$date_time)
swallowplot$date_time <- gsub("-.*", "", swallowplot$date_time)

# renaming the column ´date_time´ to ´month´, because the month is all we have left
swallowplot <- rename(swallowplot, month = date_time)

# converting the column ´month´ from characters to numbers
swallowplot$month <-  as.numeric(swallowplot$month)
```

**2.3** Check the structure of the data. The beginning of the output should look something like the example below (although the exact appearance might differ, depending on when you downloaded the data).

``` r
str(swallowplot)
```

``` r
Classes ‘finbif_occ’ and 'data.frame':  4724 obs. of  13 variables:
 $ record_id              : chr  "http://tun.fi/JX.1448957#83" "http://tun.fi/JX.1507952#45" "http://tun.fi/JX.1543606#3" "http://tun.fi/JX.1543594#3" ...
 $ scientific_name        : chr  "Hirundo rustica Linnaeus, 1758" "Hirundo rustica Linnaeus, 1758" "Hirundo rustica Linnaeus, 1758" "Hirundo rustica Linnaeus, 1758" ...
 $ abundance              : int  5 1 2 1 NA NA 3 NA 1 6 ...
 $ lat_wgs84              : num  60.2 60.3 58.3 58.8 64.3 ...
 $ lon_wgs84              : num  25 20 22 23.7 23.6 ...
 $ date_time              : Date, format: "2022-10-15" "2022-10-09" "2022-10-06" "2022-10-04" ...
 $ coordinates_uncertainty: num  1000 5000 1 1 10000 80 1 100 1 1 ...
 $ any_issues             : logi  FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ requires_verification  : logi  FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ requires_identification: logi  FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ record_reliability     : chr  "UNDEFINED" "UNDEFINED" "UNDEFINED" "UNDEFINED" ...
 $ record_quality         : chr  "Unassessed" "Unassessed" "Unassessed" "Unassessed" ...
 $ bio_province           : chr  "Uusimaa (U)" "Ahvenanmaa (A)" NA NA ...
```

**2.4** Next, let's remove observations with missing values for region (NA in the column `bio_province`) and count observations by region and by month.

``` r
swallowplot_counts <- swallowplot %>% 
  filter(!is.na(bio_province)) %>% 
  group_by(month, bio_province) %>% 
  summarise(count = n())
```

Ok! Now we're ready to create some plots.

### **3. Exercises**

**3.1** Make a bar plot of the observation counts by region using `swallowplot_counts`. Hints: use `geom_col()`. Check `swallowplot_counts` to see how the column with observations is called.

``` r
# Write the answer in your R script.
```

**3.2** What about a similar bar plot of observations but by month?

``` r
# Write the answer in your R script.
```

**3.3** Next, let's combine the above and make a line plot that shows month on the x axis, counts on the y axis, and the lines are coloured by region (`bio_province`). Hint: use `geom_line()`.

``` r
# Write the answer in your R script.
```

**3.4.** Not looking too bad, but let's make the plot look nicer by labelling the y axis 'observations' and giving the plot a title 'Barn swallows by region'

``` r
# Write the answer in your R script
```

### **4. Saving and exporting your script**

If you don't remember how to save and export your data from RStudio, follow the instructions set out in the **Starting with Data exercise sheet** (steps 7.3 and 7.4).

That's it in terms of exercises! Depending on the course schedule, there may be a chance to go through the solutions during the beginning of Day 3. However, if you're attending a two-day course and feel unsure about how to solve some of the problems above, you can have a look at the completed exercise sheets on eLearn.

Thanks for joining the course (so far!) and we hope you've found the contents useful!
